"""adicioonar coluna ativo

Revision ID: 057a111c4c5c
Revises:
Create Date: 2026-08-20 18:38:25.758771

This revision is intentionally a no-op because the SQLite database already
contains the expected schema and the previous autogenerated migration tried to
remove an unnamed foreign key, which is not valid in SQLite.
"""

from typing import Sequence, Union


revision: str = "057a111c4c5c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
