"""adicioonar coluna 
ativo

Revision ID: 1c82f41b3d35
Revises: 057a111c4c5c
Create Date: 2026-08-20 18:50:08.752045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c82f41b3d35'
down_revision: Union[str, Sequence[str], None] = '057a111c4c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
